-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TAREA1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TAREA1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TAREA1` DEFAULT CHARACTER SET utf8 ;
USE `TAREA1` ;

-- -----------------------------------------------------
-- Table `TAREA1`.`TBL_ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TAREA1`.`TBL_ROL` (
  `ROL` VARCHAR(40) NOT NULL,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ROL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TAREA1`.`TBL_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TAREA1`.`TBL_USUARIO` (
  `USUARIO` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(40) NOT NULL,
  `CORREO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TAREA1`.`TBL_ROL_TBL_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TAREA1`.`TBL_ROL_TBL_USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TBL_ROL_ROL` VARCHAR(40) NOT NULL,
  `TBL_USUARIO_USUARIO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_ROL_TBL_USER_TBL_ROL`
    FOREIGN KEY (`TBL_ROL_ROL`)
    REFERENCES `TAREA1`.`TBL_ROL` (`ROL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_ROL_TBL_USER_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_USUARIO`)
    REFERENCES `TAREA1`.`TBL_USUARIO` (`USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TBL_ROL_TBL_USER_TBL_ROL_idx` ON `TAREA1`.`TBL_ROL_TBL_USER` (`TBL_ROL_ROL` ASC) VISIBLE;

CREATE INDEX `fk_TBL_ROL_TBL_USER_TBL_USUARIO1_idx` ON `TAREA1`.`TBL_ROL_TBL_USER` (`TBL_USUARIO_USUARIO` ASC) VISIBLE;

CREATE UNIQUE INDEX `UX_TBL_ROL_TBL_USER` USING BTREE ON `TAREA1`.`TBL_ROL_TBL_USER` (`TBL_USUARIO_USUARIO`, `TBL_ROL_ROL`) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
